### ISSUE TITLE
Variants in error printed with ocaml syntax

### ISSUE THREAD

**Issue by joprice** [reasonml/reason#2203] opened 2018-09-30 17:39 UTC
In the error below, JSONObject and JSONArray are printed without parens. I'm new to reason and ocaml, but as far as I can tell, this is valid ocaml but reason requires parens in this case.

```reason
  10 │
  11 │ let getUntypedValue = () =>
  12 │   switch (Js.Json.classify(getUntypedValue())) {
  13 │     | Js.Json.JSONNumber(n) => `Float(n)
  14 │     | Js.Json.JSONString(s) => `String(s)
  15 │     /*| _ => failwith("unreachable")*/
  16 │   };
  17 │
  18 │ let test () =

  You forgot to handle a possible value here, for example:
(JSONFalse|JSONTrue|JSONNull|JSONObject _|JSONArray _)
```

**Comment by anmonteiro** [comment] 2024-07-11 19:50
Duplicate of https://github.com/reasonml/reason/issues/531

**Closed by anmonteiro** 2024-07-11 19:50 UTC
