### ISSUE TITLE
Rfmt mangles partial application of operators

### ISSUE THREAD

**Issue by feihong** [reasonml/reason#2728] opened 2023-11-02 15:31 UTC
```reason
Js.log("45" |> (++)(_, "%"));
```

Turns into

```
Js.log("45" |> _ ++ "%");
```
Which doesn't compile.

[Melange playground link](https://melange.re/v2.0.0/playground/?language=Reason&code=SnMubG9nKCI0NSIgfD4gKCsrKShfLCAiJSIpKTs%3D&live=off)

Note that if it's not an operator, it's fine. For example, this won't get mangled:

```reason
Js.log("45" |> String.cat(_, "%"));
```

**Comment by anmonteiro** [comment] 2024-07-28 06:21
duplicate of #2492

**Closed by anmonteiro** 2024-07-28 06:21 UTC
