### ISSUE TITLE
Polymorphic variant type should break line

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1674] opened 2017-11-30 06:51 UTC
Repro:

```reason
type foo = [ | `utf8 | `my_name]
```

Should format to

```reason
type foo = [
  | `utf8
  | `my_name
]
```

Though using the same heuristics as normal variants might not be good, since poly variants can be inlined:

```reason
external readFileSync :
  (~name: string, [@bs.string] [ | `utf8 | [@bs.as "ascii"] `my_name]) => string =
  "";
```

**Comment by anmonteiro** [comment] 2024-07-12 20:57
Duplicate of #2706, fix in #2708

**Closed by anmonteiro** 2024-07-12 20:57 UTC
Labels: KIND: FEATURE REQUEST, Printer
