### ISSUE TITLE
Idea: change `Include` to `...`

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1214] opened 2017-04-14 04:57 UTC
This helps distinguish between `include` and `open`
```
module Foo = {
   ...Bar;
   ...Baz with somethingSomething
};
```

**Comment by jordwalke** [comment] 2017-04-14 05:25
I had a similar thought.

**Comment by IwanKaramazow** [comment] 2017-04-14 05:40
I was thinking the same while watching your talks.

**Comment by hcarty** [comment] 2017-04-14 05:53
TBH it looks kind of line-noisy since there is no direct surrounding context, but that's possibly offset by the consistency with the rest of the `...` uses.

**Comment by ajhyndman** [comment] 2017-05-23 13:44
A comment as an outsider (I have watched some of the recent talks with interest, but haven't written anything with Reason yet):

My first impression of `include` was that it was intended to replace `import` as a syntax feature.  `...` would definitely obliterate any chance of that confusion.

**Comment by jdhorwitz** [comment] 2017-06-19 02:44
I would like to work on this, do we still want to move forward with this?

**Comment by SanderSpies** [comment] 2017-06-19 06:58
@jdhorwitz Great! We would like to have it backwards compatible, so keep that in mind.

**Comment by kennetpostigo** [comment] 2017-08-03 14:46
Has this landed? Reason-React is using this syntax already?

**Comment by chenglou** [comment] 2017-08-03 19:19
that's the ordinary record spread. I'm proposing it for modules. Still a great task to try!

**Comment by jdhorwitz** [comment] 2017-08-04 13:06
I could help you with this @kennetpostigo , I'm not exactly sure where to start.

**Comment by anmonteiro** [comment] 2024-07-07 22:11
`include` has evolved in recent OCaml versions and it becomes clearer to have an actual keyword.

**Closed by anmonteiro** 2024-07-07 22:11 UTC
Labels: RFC, Parser
