### ISSUE TITLE
[feature] more succinct syntax for first class module?

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#1685] opened 2017-12-06 06:54 UTC
Note the new map API in BuckleScript would be like

```ocaml
module N = (val Bs.Cmp.make (fun [@bs] (x : int) y  -> Pervasives.compare x y))
let empty = Bs.Map.emtpy (module N)
``` 

I wonder in Reason, it would be possible to remove the `val`.
like below?
```ocaml
module N =  Bs.Cmp.make ((. x : int, y) => Pervasives.compare(x,y) );
let empty = Bs.Map.empty(module N);
```
cc @cristianoc

**Comment by jordwalke** [comment] 2017-12-07 08:12
The `val` is such a weird syntax, so I agree that we should think of a better more concise first class module syntax.
I currently use "module destructuring" to avoid the `val` keyword, but it's already so laborious even in that case because of all the extra mandatory parens.

```
let myFunction = (x, (module Foo) : (module FooSig)) => {

};
```


In your proposal for automatically converting from first class to second class modules:

```reason
module N = Bs.Cmp.make ((. x : int, y) => Pervasives.compare(x,y) );
```

How would we divide up the parsing grammar rules? We can't easily say "anything that is an expression on right hand side of `module X =` should be automatically demoted to second class module, and nothing else should be demoted to second class module, because of the following case:

```
module N = Bs.Cmp;
```

It appears that `Bs.Cmp` is an expression, but it's actually a module. We'd have to create some special parsing classifications for "expressions that are never confused with modules". We would forbid anything that is a variant for example.


```reason
module N = Bs.Cmp.make ((. x : int, y) => Pervasives.compare(x,y) );
```

This is possible but kind of tricky to maintain in the parser. Can you think of any edge cases?

**Comment by jordwalke** [comment] 2017-12-07 08:16
Just to brainstorm some other ideas: How would you feel about using a familiar syntax for first class modules, by "packing" and "unpacking" them from records with a single field named `module`?
It's possible because as it is, `module` is a reserved keyword and not tolerated in records so the grammar real estate is available.


```reason
let myFirstClassModule = {module: String};
module StringCopy = myFirstClassModule.module;
```

(You'd still need to figure out type annotations but at least that offers a symmetric syntax for first class modules packing/unpacking). It's not much more concise, but it *is* more familiar.

**Comment by anmonteiro** [comment] 2024-07-21 05:25
duplicate of #1601

**Closed by anmonteiro** 2024-07-21 05:25 UTC
Labels: KIND: FEATURE REQUEST, Parser
