### ISSUE TITLE
User defined index operators

### ISSUE THREAD

**Issue by EduardoRFS** [reasonml/reason#2643] opened 2021-02-05 18:56 UTC
Currently there is no way to define index operators in Reason only in OCaml, which is a feature available since 4.06

https://ocaml.org/manual/indexops.html

```reason
let ( .%{} ) = (tabl, index) => find(tabl, index)
```

**Comment by anmonteiro** [comment] 2024-07-11 20:03
Duplicate of #2432

**Closed by anmonteiro** 2024-07-11 20:03 UTC
