### ISSUE TITLE
Incorrect conversion of custom fat arrow operator

### ISSUE THREAD

**Issue by jwhitley** [reasonml/reason#2416] opened 2019-06-01 17:25 UTC
### Summary

`refmt` doesn't convert uses of an OCaml custom fat arrow operator `let (=>) ...` to Reason sensibly.

A larger issue may exist around whether a automatic syntactic conversion even exists for this case.  A potential workaround is not evident from the Reason docs.

### Details and Example

The [opal parser combinator](https://github.com/pyrocat101/opal) defines the infix operator `=>`: [see opal.ml line 81](https://github.com/pyrocat101/opal/blob/master/opal.ml#L81).

`refmt` (and reason-tools) fail to convert this sanely, e.g.:

**OCaml**
```ocaml
let (=>) x f = x >>= fun r -> return (f r)
```

**Reason**
```reason
let (=>) = (x, f) => x >>= ((r) => return(f(r)));
```

The generated Reason code is invalid.  Opal's custom fat-arrow operator is silently left unchanged, which collides with Reason's choice to switch arrow function definition from thin arrow to fat arrow.  This causes obscure syntax errors later in the code at opal's point-of-use of its custom `=>` operator.  ([See use in `chainr1`](https://github.com/pyrocat101/opal/blob/master/opal.ml#L120))

### Suggestions

At minimum, `refmt` shouldn't let this invalid conversion pass silently – a warning or error should result.

I attempted a naive swap of custom `=>` (OCaml) for custom `->` (Reason), but the thin-arrow definition simply produced a syntax error in the Reason code.

**Comment by anmonteiro** [comment] 2019-06-01 17:48
https://github.com/facebook/reason/pull/1944 is open to address this

**Comment by anmonteiro** [comment] 2024-07-28 06:39
duplicate of #1941

**Closed by anmonteiro** 2024-07-28 06:39 UTC
