### ISSUE TITLE
[website] Command clicking on nav items should open links in new tabs

### ISSUE THREAD

**Issue by steveluscher** [reasonml/reason#1347] opened 2017-08-02 03:44 UTC
Command-clicking on these opens the target links in the same tab, when it should open them in new tabs.

<img width="718" alt="screen shot 2017-08-01 at 8 44 03 pm" src="https://user-images.githubusercontent.com/13243/28856858-398bd9a2-76fa-11e7-9b09-4e8813647723.png">

**Comment by bassjacob** [comment] 2017-08-02 08:01
@steveluscher likely related to https://github.com/reasonml/reasonml.github.io/issues/65. Is this maybe a duplicate of that issue?

**Comment by steveluscher** [comment] 2017-08-02 16:02
Sure is! I searched and searched before filing this, but I didn't use the words ‘middle click.’

**Closed** 2024-07-07 23:56 UTC
Labels: Documentation
