### ISSUE TITLE
Support for `?` operator for option/result types

### ISSUE THREAD

**Issue by sgrove** [reasonml/reason#1928] opened 2018-05-15 12:52 UTC
Dealing with deeply nested, highly optional data structures (*very* common in real-world GraphQL where everything is nullable by default) is fairly tedious right now, and the feedback from the workshop was that having to use `switch` at each subsequent level was very cumbersome, and a custom infix operator was a bit mystical if it was defined inline and then refmt adds a lot of whitespace around it.

It might be nice to adopt[ Rust's `?` operator,](https://m4rw3r.github.io/rust-questionmark-operator) possibly even as a simple syntax expansion.

The goal would be to turn something like this (real-world example):

```reason
let make = _children => {
  render: (_) => {
    let reposQuery = GetRepositories.make(~name="sgrove", ());
    <GetRepositoriesQuery variables=resposQuery##variables>
      ...(
           ({result}) =>
             switch result {
             | NoData => <div> (ReasonReact.string("No Data")) </div>
             | Loading => <div> (ReasonReact.string("Loading")) </div>
             | Error(error) => <div> (ReasonReact.string(error)) </div>
             | Data(response) =>
               <div>
                 (
                   switch result##viewer {
                   | None => ReasonReact.string("No viewer")
                   | Some(viewer) =>
                     switch viewer##repositories {
                     | None => ReasonReact.string("No repos")
                     | Some(repositories) =>
                       switch repositories##edges##nodes {
                       | None => ReasonReact.string("No nodes")
                       | Some(nodes) =>
                         ReasonReact.array(
                           Array.map((
                             node =>
                               switch node {
                               | None => ReasonReact.string("Null repo")
                               | Some(node) =>
                                 switch node##name {
                                 | None => ReasonReact.string("No repo name")
                                 | Some(name) => ReasonReact.string(name)
                                 }
                               },
                             nodes
                           ))
                         )
                       }
                     }
                   }
                 )
               </div>
             }
         )
    </GetRepositoriesQuery>;
  }
}
```

Into this:

```reason
let make = _children => {
  render: (_) => {
    let reposQuery = GetRepositories.make(~name="sgrove", ());
    <GetRepositoriesQuery variables=resposQuery.variables>
      ...(
           ({result}) =>
             switch result {
             | NoData => <div> (string("No Data")) </div>
             | Loading => <div> (string("Loading")) </div>
             | Error(error) => <div> (string(error)) </div>
             | Data(response) =>
               <div>
                 (
                   switch result##viewer?##repositories?##edges##nodes {
                   | None => nullElement
                   | Some(nodes) => array(
                     Array##map((node =>
                         switch node?##name {
                         | None => string("Null repo or name")
                         | Some(name) => string(name)
                         },
                       nodes
                     ))
                   )
                 })
               </div>
             }
         )
    </GetRepositoriesQuery>;
  }
};
```

Rust's operator works on both Result and Option types which would likely be difficult, and Reason also has record-field-access and object-field-access syntax, so there's plenty to consider when introducing syntax support for this.

**Comment by cristianoc** [comment] 2018-05-15 13:12
So it looks like the desired effect is a more compact form of the following use of accessor functions.

```reason
let viewer = x => x#viewer;

let repositories = x => x#repositories;

let edges = x => x#edges;

let nodes = x => x#nodes;

let (|>?) = (x, access) =>
  switch (x) {
  | None => None
  | Some(v) => access(v)
  };

let (|>+) = (x, access) =>
  switch (x) {
  | None => None
  | Some(v) => Some(access(v))
  };

let test = x => Some(x) |>? viewer |>? repositories |>+ edges |>? nodes;
```

**Comment by grsabreu** [comment] 2018-05-15 14:12
Currently what I'm using to do this is to use a bind operator,

```
result##viewer >>= (viewer => viewer##repositories) >>= (repositories => repositories##edges) >>= (edges => edges##nodes)
```

But stills a bit overwhelming to write. Would be nice to be able to have some kind to have a more succinct way to write that.

Maybe this is more a `bucklescript`'s concern.

**Comment by hcarty** [comment] 2018-05-15 16:14
If you don't mind using a ppx syntax extension, both [ocaml-monadic](https://github.com/zepalmer/ocaml-monadic) and [ppx_let](https://github.com/janestreet/ppx_let) provide some shorthand syntax for `let` bindings.

I'm not aware of anything supporting this now, but `##` is handled as a special case in syntax extensions.  It should be possible to provide some basic syntax using `##?`, for example, as a shorthand for `>>=` but acting like `##` with respect to precedence.  That could be a useful way to experiment with the idea without having to hack on Reason itself.

**Comment by jordwalke** [comment] 2018-05-16 08:46
@cristianoc was the `|>+` operator necessary?

I believe there's a JS proposal for `field.?value`. It could make sense to add `field##?value` and `field#?value` and the same time.

**Comment by cristianoc** [comment] 2018-05-16 09:07
@jordwalke the `|>+` operator was necessary because `edges` is not optional.

**Comment by guilhermedecampo** [comment] 2018-05-18 14:57
Would be awesome to add `x##?y` and `obj#?method`!

**Comment by Gregoirevda** [comment] 2018-05-22 19:00
I'm looking into this since the GraphQL workshop @sgrove.
I'm planning on making a PR in graphql_ppx to generate getters for each field so you can:

```reason
let |•| = (result, default_) => 
switch result {
  | Some(result) => result
  | None => default_
};

let nodes = (result |. viewer |. repositories |. edges |. nodes) |•| [||];
```

Since we know if each field is optional or not, it would avoid all user defined getters (pretty long) and the `|>+`handling too.

I was wondering what the impact would be on the JS bundle size. Aren't `bs.deriving abstract` generated getters and setters increasing your JS bundle a lot?

**Comment by chenglou** [comment] 2018-05-28 18:02
@Gregoirevda you probably know now, but I'll write it here for others: `bs.deriving abstract` doesn't generate any noisy output

**Comment by cloudkite** [comment] 2018-06-06 09:49
Here is the [Javascript Proposal](https://github.com/tc39/proposal-optional-chaining) which is using the `?.` operator ([swift](https://docs.swift.org/swift-book/LanguageGuide/OptionalChaining.html) also uses `?.`).  So for symmetry maybe `?#` and `?##` would make sense? rather than `#?` and `##?`

**Comment by cristianoc** [comment] 2018-06-07 04:32
Looking at the swift version, but others as well, it seems that `_ ?. fld` has both of these types:
```reason
option(t) => option(t)
t => option(t)
```
so strictly speaking it's an extension of the language. This means one needs to reach  a little deep to implement it, and can't just be a JSX transform.

Also wondering what this means for type inference, and principal types in particular.
Also not clear what it should do on nested optionals, there seems to be some ambiguity there.

**Comment by cloudkite** [comment] 2018-06-07 07:43
@cristianoc I have no idea if this is feasible but could it be transformed into a switch?

For example given the following types:

```
type c = { thing: string };
type b = { c: option(c) };
type a = { b: option(b) };
let a = { b: Some({ c: Some({ thing: "hello" }) }) };
```

When you write an optional chained expression ie:

```
let z = a.?b.?c.thing
```

Reason would transform this to a switch:
```
let z = switch (a.b) {
| None => None
| Some(b_) => 
    switch (b_.c) {
    | None => None
    | Some(c_) => Some(c_.thing)
    }
};
```

This would be great for accessing properties on deeply optional records.

**Comment by cloudkite** [comment] 2018-06-07 07:50
Also feel like this should only work on optional types rather than with the result type as well. Which I'm guessing would make it easier to make this a syntax expansion? This also aligns with the behaviour in swift and js.

**Comment by Gregoirevda** [comment] 2018-06-07 08:40
I started implementing this with the help of @IwanKaramazow

**Comment by cloudkite** [comment] 2018-06-07 10:07
@Gregoirevda Awesome!! This is probably a seperate change but could be worth keeping in mind. 
https://github.com/tc39/proposal-nullish-coalescing and its also implemented in swift http://www.codingexplorer.com/nil-coalescing-swift/

**Comment by chenglou** [comment] 2018-06-07 19:28
@cristianoc we'll only allow it for optionals. Allowing for non-optionals makes loose guess-based usages too easy, e.g. "yeah why not, let's just use it here".

Also, `?##` isn't easily doable because "hash something" is actually part of the language's sugar for custom extension. So `##?` is easy but `?##` means adding a new syntax to Reason (that's incompatible with OCaml usage of BuckleScript). We should probably postpone adding this. There are other concerns I'm thinking about.

`?.` is too bad because I was thinking we could support trailing question mark for variable names. But I guess `foo?.bar` is better than `foo.?bar` because the former indicates that `foo` is the optional one. On second thought, we might still able to support `foo?` variable name anyway.

The other concern I have is the coding pattern where folks do:

```reason
let a = foo?.bar?.baz;
let b = foo?.bar;
...
```

Aka repeatedly accessing a long chain. But maybe it won't be prevalent.

Implementation-wise, I'm thinking that we should turn `?.` into a first-class infix operator that desugars to @cristianoc's `|>?` (aka map). Visually, the `?.` operator won't need spaces around it.

We don't need the version that wraps the value into a Some for now (aka bind) for now.

**Comment by cristianoc** [comment] 2018-06-08 03:45
Here's a test that a proposal should pass:
```reason
  type t = { a : int, b : option(t) };
  let test = (x:t) => x.b.b.a;
```
for appropriate replacements of `.` with whatever operator is used.

**Comment by cristianoc** [comment] 2018-08-30 12:30
Here's an experiment for auto-unwrapping options when accessing fields: https://github.com/cristianoc/ocaml/pull/1.

**Comment by anmonteiro** [comment] 2024-07-11 20:21
Duplicate of #1345

**Closed by anmonteiro** 2024-07-11 20:21 UTC
Labels: RFC, Parser
