### ISSUE TITLE
val keyword / first-class modules

### ISSUE THREAD

**Issue by cknitt** [reasonml/reason#2382] opened 2019-04-15 05:45 UTC
@IwanKaramazow As discussed in person/on Discord:

Usually you don't see the `val` keyword in Reason, as `let` is used instead.

However, I came across the `val` keyword in the context of first-class modules when creating https://github.com/cca-io/re-logger, a simple logger library with a pluggable logger implementation.

The library is used like this:

```re
module Log = (val ReLogger.make(__MODULE__));

Log.info("Some log message");
```

It seems that the syntax for

```re
module Log = (val ReLogger.make(__MODULE__));
```

is a leftover from OCaml.

- Can the parentheses be removed?
- Can/should a different keyword be used?

Also, it would be great to have some documentation about first-class modules in Reason.

**Comment by anmonteiro** [comment] 2024-07-21 05:24
duplicate of #1601

**Closed by anmonteiro** 2024-07-21 05:24 UTC
Labels: Syntax, RFC
