### ISSUE TITLE
convert ?-: conditionals to if-else

### ISSUE THREAD

**Issue by jberdine** [reasonml/reason#565] opened 2016-06-06 23:21 UTC
If a ?-: conditional has at least one argument that needs braces, the ?-: conditional should be converted to if-else.  The converse also seems good: convert if-else expressions to ?-: when all three arguments are simple.

Going further, to converting any ?-: that doesn't fit on one line is also probably a good idea, but I guess harder to implement.

**Comment by jordwalke** [comment] 2016-06-14 08:53
I hadn't considered this. I like it.
Right now, there is one benefit to the current approach for ternary conditionals. They are always preserved by the pretty printer no matter what because they have a separate AST representation. However, there are many simple `if/then` expressions in OCaml code that would look so much better if converted to ternaries, so I like your proposal.

**Comment by jberdine** [comment] 2016-06-14 10:02
Actually, if simple if-else expressions format on one line, then I think that the value of ternaries drops considerably.  But that's just probably just my preference.

The under-riding consideration here is that it is generally good if there are fewer equivalent ways to write the same thing, so that programmers don't have to spend time thinking about which to choose.  There are always more than the syntax can help with, but every little helps.

**Comment by AppShipIt** [comment] 2016-06-14 21:05
> The under-riding consideration here is that it is generally good if there are fewer equivalent ways to write the same thing, so that programmers don't have to spend time thinking about which to choose.

I wish this were the motto of a (more functional) language besides Python 💓 The potential for that to be Reason is why I'm watching closely. I feel like [TIMTOWDTI](https://en.wikipedia.org/wiki/There%27s_more_than_one_way_to_do_it) is a consternation to many developers who just want <q>one—and preferably only one—obvious (right) way to do it.</q>

**Comment by bsansouci** [comment] 2016-06-14 21:14
I'd be in favor of not having ternary. Especially since you can write an if in one line, without braces.

**Comment by jaredly** [comment] 2018-06-14 15:11
see also #1700

**Comment by anmonteiro** [comment] 2024-07-11 20:34
Duplicate of #1700

**Closed by anmonteiro** 2024-07-11 20:34 UTC
Labels: KIND: FEATURE REQUEST, Printer
