### ISSUE TITLE
Unboxed call at toplevel loses the`@bs` annotation (by putting it outside the expression).

### ISSUE THREAD

**Issue by cristianoc** [reasonml/reason#2610] opened 2020-07-22 09:32 UTC
`foo(. bar)` at toplevel

see https://github.com/BuckleScript/syntax/issues/55

**Comment by anmonteiro** [comment] 2024-07-28 05:34
duplicate of https://github.com/reasonml/reason/issues/2565

**Closed by anmonteiro** 2024-07-28 05:34 UTC
