### ISSUE TITLE
[refmt] ml => re => parse error on gen_js_api interface file

### ISSUE THREAD

**Issue by Lupus** [reasonml/reason#2430] opened 2019-07-11 13:02 UTC
I have the following code in OCaml (a piece of nodejs bindings for jsoo using gen_js_api):

```ocaml
module Console: sig
  [@@@js.implem
    Ojs.set Ojs.global "Console" (require "console")
  ]

  val log: ('a, unit, string, unit) format4 -> 'a
  [@@js.custom
       val log_internal: string -> unit
         [@@js.global "Console.log"]
       let log format = Format.ksprintf log_internal format
  ]
end
```

When printing it to Reason using refmt (Reason 3.3.7 @ 43efc14) it produces the following seeming valid code:

```reason
module Console: {
  [@js.implem Ojs.set(Ojs.global, "Console", require("console"))];

  [@js.custom
    [@js.global "Console.log"] external log_internal: string => unit = ;
    let log = format => Format.ksprintf(log_internal, format)
  ]
  let log: format4('a, unit, string, unit) => 'a;
};
```

But it does not parse back:

```
$ esy refmt --parse=re --print=ml
module Console: {
  [@js.implem Ojs.set(Ojs.global, "Console", require("console"))];

  [@js.custom
    [@js.global "Console.log"] external log_internal: string => unit = ;
    let log = format => Format.ksprintf(log_internal, format)
  ]
  let log: format4('a, unit, string, unit) => 'a;
};
File "", line 5, characters 4-30:
Error: Syntax error
```

If I add `""` after `=` on `external` line, another error is produced:
```
$ esy refmt --parse=re --print=ml
module Console: {
  [@js.implem Ojs.set(Ojs.global, "Console", require("console"))];

  [@js.custom
    [@js.global "Console.log"] external log_internal: string => unit = "";
    let log = format => Format.ksprintf(log_internal, format)
  ]
  let log: format4('a, unit, string, unit) => 'a;
};

File "", line 9, characters 1-2:
Error: Syntax error
```

**Comment by anmonteiro** [comment] 2024-07-21 05:29
duplicate of https://github.com/reasonml/reason/issues/2445

**Closed by anmonteiro** 2024-07-21 05:29 UTC
