### ISSUE TITLE
use topfind is not working in rtop

### ISSUE THREAD

**Issue by bentxt** [reasonml/reason#2792] opened 2024-08-19 14:37 UTC
```
rtop -init ~/.config/rtop/init.re
...
#use "topfind";
Fatal error: exception File "/Users/ben/.opam/default/lib/toplevel/topfind", line 1, characters 3-4:
Error: Unclosed "(" (opened line 1, column 0)
```

Maybe it has something to do with this topfind file seems to be written with the ocaml syntax

**Comment by anmonteiro** [comment] 2024-08-19 15:50
Dupe of #847

**Closed by anmonteiro** 2024-08-19 15:50 UTC
