### ISSUE TITLE
Erroneous type inference

### ISSUE THREAD

**Issue by arsdragonfly** [reasonml/reason#2452] opened 2019-09-22 03:12 UTC
```reason
type item = {
  id: int,
  title: string,
  completed: bool,
};
 
type state = {
  id: int, // id for a new item
  items: list(item),
};
 
[@react.component]
let make = (~title) => {
  let ({items}, dispatch) =
    React.useReducer(
      (state, action) => {
        let items =
          List.map(
            item => {id: item.id, title: item.title, completed: false},
            state.items,
          );
        {id: state.id, items};
      },
      {
        id: 1,
        items: [{id: 0, title: "Write some things to do", completed: false}],
      },
    );
  <div className="items">
    {React.array(
       Array.of_list(
         List.map(item => <div>(React.string(item.title))</div>, items),
       ),
     )}
  </div>;
};
```
![深度截图_选择区域_20190923112931](https://user-images.githubusercontent.com/4067473/65439601-728bc780-ddf5-11e9-9840-72171681d58f.png)

**Comment by anmonteiro** [comment] 2019-09-22 03:19
Looks like you're using VS Code + RLS. This should be reported in https://github.com/jaredly/reason-language-server

**Comment by arsdragonfly** [comment] 2019-09-22 03:33
Leaving Discord log here for reference.

```
 anmonteiroToday at 11:24 PM
@arsdragonfly that's also not really a bug
 
arsdragonflyToday at 11:24 PM
i.e. if I change line 19 of that minimal example to
{id: item.id, title: item.title, completed: false}
it stops working
but {id: 0, title: item.title, completed: false}
 
anmonteiroToday at 11:24 PM
the explanation is a bit weird, but type inference is left -> right
 
arsdragonflyToday at 11:24 PM
is fine
 
anmonteiroToday at 11:25 PM
and if you're accessing id, OCaml infers the last record declared in the file with a property id
 
arsdragonflyToday at 11:25 PM
but why LAST instead of ALL?
 
anmonteiroToday at 11:26 PM
because it needs to choose one
it can't infer both types
this might be better in newer versions of OCaml btw
 
arsdragonflyToday at 11:27 PM
can I put it differently
 
the__spyderToday at 11:27 PM
Well that’s probably a long discussion of type theory... it’s generally discouraged to define two records in the same scope with overlapping field names. You have to manually disambiguate in cases like this
 
anmonteiroToday at 11:27 PM
but BuckleScript is stuck on 5 year old version of OCaml
 
arsdragonflyToday at 11:28 PM
Why doesn't OCaml infer types in a row-polymorphic way
 
anmonteiroToday at 11:28 PM
records don't have row polymorphism
objects do
@arsdragonfly anyway, I should stop enumerating problems. There are a couple solutions for your case here
you can use Belt.List.map, which takes the collection as the first argument in order to (ab)use the type inference flow direction
 
arsdragonflyToday at 11:29 PM
lol
that's so funny but thanks anyway
 
anmonteiroToday at 11:30 PM
or you can annotate your item argument like (item: item) => { ... }
```

**Comment by TheSpyder** [comment] 2019-09-23 07:59
odd, when we had this discussion in Discord you indicated it was an error in compiling as well as vscode, but it [works fine on the try page](https://reasonml.github.io/try?rrjsx=true&reason=C4TwDgpgBAlsEFsoF4oG8BQVYBMBcsAdsADRZTBwA2EBAzsAE4yEDmZ2AxgPYJg3x8UAEbduVMgF8A3FgyhIUBgEN4KdORhCWpTfAR0CVGAwAUcRAEopsqBgDaAAUYRlnYADoefboQjEAXQwBKARlAGtoVFMAP0pgGksUAD4NbBDTNAsDSRIoHBMwVU4ACyTkcmwAJVd3DwBXOgganHrOCEZTSuwoUxV4PLdKX3LUzB6JqBDsuhRuyagAGRNPMLAuhYXslPQtAgAGPPiaAgAiU7zvfghBAgAzZSom3PnN-ogPGY5N7EtbTayQnenxweRmMleLwW402eygAEZvlt9IYoPZAQcjtRaFBTgB1ZhqOi8aDAEosVizYDcfLcC5QK4CCBCB5PCCSAJInpQnp-cgAHgKADcGVRlHQ6AA5ZQICDIU4zU7JbpoGpDDzKRiMZQgDYLACCWp1Hm4dwA+sYzK8essGB41uZ9DtBTAhclTGq6gxmGxHYgPMcIJZLPyAPTC5JglHWa0xyaWSQC8Ou5KyGRAA).

If in fact this doesn't cause compile errors in `bsb` then yes it should be reported to the RLS plugin not here. And all of the advice we provided, while true in general for records, wasn't relevant to the specific issue.

**Comment by arsdragonfly** [comment] 2019-09-23 15:24
@TheSpyder @anmonteiro  sorry for the confusion; there are probably TWO issues here, one being RLS not being able to yield the type of state.items, the other being that if I change `item => {id: 0, title: "", completed: false}` into `item => {id: item.id, title: item.title, completed: false}` the code no longer compiles, as the type of item is inferred to be `state`. I'll update the code and screenshot accordingly. (I originally thought that the compiler couldn't infer the type of state.items, thus leading to the compiler error.)

**Comment by arsdragonfly** [comment] 2019-09-23 15:30
example & screenshot updated.

**Comment by TheSpyder** [comment] 2019-09-23 19:45
Ok, yes. So back to what we tried to describe on discord; unfortunately this isn't reason-related it's how OCaml records work.

The problem is that record field access such as `item.id` isn't looking for a field called `id` on the variable `item` (you can see this if you open the compiled JS, it's all arrays under the hood with number indices mapped to fields). What OCaml does is look for a record field defined with the name `id` in scope, and because you've shadowed the names it finds the `type state` definition. It could (and has[1][2]) been argued that OCaml should consider _all_ field names, but for now it doesn't.

This is all much better explained in the Real World OCaml book:
http://dev.realworldocaml.org/records.html (section `Reusing Field Names`)

Packing types into modules is the usual solution, because then you can use `item.Module.id` to reference the field type which is unambiguous. [Here's your code updated to do that](https://reasonml.github.io/try?rrjsx=true&reason=LYewJgrgNgpgBASQC42HAvHA3gKCQTwAd4kNsc44BLMALmoDskAaCuJKpWegZyQCcqDAOatKAYxDBCsFHTgAjECCisAvjjUBuHDlCRYcAMpIAhijK4CxdpbY16QlvZTAe9KFT4AKZKgB0SACU6po6cDgA2gAC-DCm4kj+ktIgDDBMALo4snDApgDW8JjeAH4cXDBBGAB85JS53lgm5jD+nKg8asxwYF6E5uIAFtXobJQASvGJ-hA8MFOQ4jD83uOUcN58rT0JHGmjdbgbJ3C5HW4Y66dwADJeSfmEazc3F7WIrv5YDtRfND0Ktw-gEgTAeikZDA5PQAGamKDzbrXV7bFD+Froi48MSvShBcKvH7yNFtAEgtzaFHIm7HV6-ACMuLernccEixPoAAZAZxgQAiADqggsPCkJCGQmEPHYIF6IH5EKkUJhcHhiJgakyzI2NI2BLYAB4+gA3ODiKCmHg8ABypmAMHQ-Ox-Jq6ywUz2-lM-H4pnwLxuAEFff7-CBYQB9Tw+FEbe58fxPbzvdB1Y1UE01byemZ8QQiFNfPzAQJ8qpBQ0AelNNR62JCccbpyCGko1drOm0QA).

[1] http://gallium.inria.fr/blog/resolving-field-names/
[2] http://gallium.inria.fr/blog/resolving-field-names-2/

**Comment by davesnx** [comment] 2022-11-21 09:16
Closing since it's pointed out to not be a "bug".

**Closed by davesnx** 2022-11-21 09:16 UTC
